spring:
  datasource:
    url: jdbc:mysql://140.246.115.176:3306/jgpt?serverTimezone=Asia/Shanghai
    username: jgpt
    password: e8PNATnWNwhr6JMe
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    schema: classpath:sql/schema_h2.sql # 数据库文件C:\Users\xxx\.h2
    #    data: classpath:sql/initial.sql
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 60000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        useLocalTransactionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 101.133.140.19
    port: 6371
    password: 123456
    timeout: 3000
    jedis:
      pool:
        max-idle: 8
        max-wait: -1
        max-active: 8
        min-idle: 0

face:
  hr:
    APP_ID: 6AQm9T34mbT7cZLZX9J7eVXM2PmR5CL1GfA5SPietEWM
    APP_KEY: 9EjpcKaCx1FkVCv3zdS9pEPUDFrPhVjQyAB1Z1gW6nX6
    lib_path: D:/wwwroot/czjg/facelib/win
    pre_path: D:/wwwroot/chizhou/jg/backend/public
