spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cfxc?useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
