spring:
  datasource:
    url: jdbc:mysql://101.201.149.34:3306/js_trace?useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: T!fc!Gqy5T@wLqMA
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    schema: classpath:sql/schema_h2.sql # 数据库文件C:\Users\xxx\.h2
    #    data: classpath:sql/initial.sql
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 60000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        useLocalTransactionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations:
    - classpath:/mapper/*.xml

server:
  port: 8000

websocket:
  server:
    enable: true
    port: 7755

tcp:
  server:
    enable: true
    port: 7611
  client:
    enable: true
    ip: 127.0.0.1
    port: 7615
