spring:
  profiles:
    active: dev
    include: pay,rkey

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations:
    - classpath:/mapper/*.xml

server:
  port: 8884

websocket:
  server:
    enable: false
    port: 7755

tcp:
  server:
    enable: true
    port: 8885
  client:
    enable: false
    ip: 112.30.143.184
    port: 8885

sign:
  key: Yss52KA3diLaB0
