package org.yzh.web.model.entity;

import java.math.BigDecimal;
import java.util.Date;

public class CzJsStudentReserves {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.stunum
     *
     * @mbggenerated
     */
    private String stunum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.inscode
     *
     * @mbggenerated
     */
    private String inscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.school_name
     *
     * @mbggenerated
     */
    private String schoolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.plat_user_id
     *
     * @mbggenerated
     */
    private Integer platUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.cardtype
     *
     * @mbggenerated
     */
    private Byte cardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.idcard
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.nationality
     *
     * @mbggenerated
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.sex
     *
     * @mbggenerated
     */
    private Byte sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.photo
     *
     * @mbggenerated
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.fingerprint
     *
     * @mbggenerated
     */
    private String fingerprint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.id_card_img1
     *
     * @mbggenerated
     */
    private String idCardImg1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.id_card_img2
     *
     * @mbggenerated
     */
    private String idCardImg2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.report_img
     *
     * @mbggenerated
     */
    private String reportImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.busitype
     *
     * @mbggenerated
     */
    private Byte busitype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.drilicnum
     *
     * @mbggenerated
     */
    private String drilicnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.fstdrilicdate
     *
     * @mbggenerated
     */
    private Date fstdrilicdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.perdritype
     *
     * @mbggenerated
     */
    private String perdritype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.traintype
     *
     * @mbggenerated
     */
    private String traintype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.apply_fee
     *
     * @mbggenerated
     */
    private BigDecimal applyFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.bank_account
     *
     * @mbggenerated
     */
    private String bankAccount;
    private String payToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.info_check
     *
     * @mbggenerated
     */
    private Integer infoCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.manager_check
     *
     * @mbggenerated
     */
    private Integer managerCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.exam_check
     *
     * @mbggenerated
     */
    private Integer examCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.shift_seq
     *
     * @mbggenerated
     */
    private String shiftSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.shift_info
     *
     * @mbggenerated
     */
    private String shiftInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.order_status
     *
     * @mbggenerated
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_student_reserves.deleted_at
     *
     * @mbggenerated
     */
    private Date deletedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.id
     *
     * @return the value of cz_js_student_reserves.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.id
     *
     * @param id the value for cz_js_student_reserves.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.order_id
     *
     * @return the value of cz_js_student_reserves.order_id
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.order_id
     *
     * @param orderId the value for cz_js_student_reserves.order_id
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.stunum
     *
     * @return the value of cz_js_student_reserves.stunum
     * @mbggenerated
     */
    public String getStunum() {
        return stunum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.stunum
     *
     * @param stunum the value for cz_js_student_reserves.stunum
     * @mbggenerated
     */
    public void setStunum(String stunum) {
        this.stunum = stunum == null ? null : stunum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.inscode
     *
     * @return the value of cz_js_student_reserves.inscode
     * @mbggenerated
     */
    public String getInscode() {
        return inscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.inscode
     *
     * @param inscode the value for cz_js_student_reserves.inscode
     * @mbggenerated
     */
    public void setInscode(String inscode) {
        this.inscode = inscode == null ? null : inscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.school_name
     *
     * @return the value of cz_js_student_reserves.school_name
     * @mbggenerated
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.school_name
     *
     * @param schoolName the value for cz_js_student_reserves.school_name
     * @mbggenerated
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.plat_user_id
     *
     * @return the value of cz_js_student_reserves.plat_user_id
     * @mbggenerated
     */
    public Integer getPlatUserId() {
        return platUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.plat_user_id
     *
     * @param platUserId the value for cz_js_student_reserves.plat_user_id
     * @mbggenerated
     */
    public void setPlatUserId(Integer platUserId) {
        this.platUserId = platUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.cardtype
     *
     * @return the value of cz_js_student_reserves.cardtype
     * @mbggenerated
     */
    public Byte getCardtype() {
        return cardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.cardtype
     *
     * @param cardtype the value for cz_js_student_reserves.cardtype
     * @mbggenerated
     */
    public void setCardtype(Byte cardtype) {
        this.cardtype = cardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.idcard
     *
     * @return the value of cz_js_student_reserves.idcard
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.idcard
     *
     * @param idcard the value for cz_js_student_reserves.idcard
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.nationality
     *
     * @return the value of cz_js_student_reserves.nationality
     * @mbggenerated
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.nationality
     *
     * @param nationality the value for cz_js_student_reserves.nationality
     * @mbggenerated
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.name
     *
     * @return the value of cz_js_student_reserves.name
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.name
     *
     * @param name the value for cz_js_student_reserves.name
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.sex
     *
     * @return the value of cz_js_student_reserves.sex
     * @mbggenerated
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.sex
     *
     * @param sex the value for cz_js_student_reserves.sex
     * @mbggenerated
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.phone
     *
     * @return the value of cz_js_student_reserves.phone
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.phone
     *
     * @param phone the value for cz_js_student_reserves.phone
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.address
     *
     * @return the value of cz_js_student_reserves.address
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.address
     *
     * @param address the value for cz_js_student_reserves.address
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.photo
     *
     * @return the value of cz_js_student_reserves.photo
     * @mbggenerated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.photo
     *
     * @param photo the value for cz_js_student_reserves.photo
     * @mbggenerated
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.fingerprint
     *
     * @return the value of cz_js_student_reserves.fingerprint
     * @mbggenerated
     */
    public String getFingerprint() {
        return fingerprint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.fingerprint
     *
     * @param fingerprint the value for cz_js_student_reserves.fingerprint
     * @mbggenerated
     */
    public void setFingerprint(String fingerprint) {
        this.fingerprint = fingerprint == null ? null : fingerprint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.id_card_img1
     *
     * @return the value of cz_js_student_reserves.id_card_img1
     * @mbggenerated
     */
    public String getIdCardImg1() {
        return idCardImg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.id_card_img1
     *
     * @param idCardImg1 the value for cz_js_student_reserves.id_card_img1
     * @mbggenerated
     */
    public void setIdCardImg1(String idCardImg1) {
        this.idCardImg1 = idCardImg1 == null ? null : idCardImg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.id_card_img2
     *
     * @return the value of cz_js_student_reserves.id_card_img2
     * @mbggenerated
     */
    public String getIdCardImg2() {
        return idCardImg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.id_card_img2
     *
     * @param idCardImg2 the value for cz_js_student_reserves.id_card_img2
     * @mbggenerated
     */
    public void setIdCardImg2(String idCardImg2) {
        this.idCardImg2 = idCardImg2 == null ? null : idCardImg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.report_img
     *
     * @return the value of cz_js_student_reserves.report_img
     * @mbggenerated
     */
    public String getReportImg() {
        return reportImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.report_img
     *
     * @param reportImg the value for cz_js_student_reserves.report_img
     * @mbggenerated
     */
    public void setReportImg(String reportImg) {
        this.reportImg = reportImg == null ? null : reportImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.busitype
     *
     * @return the value of cz_js_student_reserves.busitype
     * @mbggenerated
     */
    public Byte getBusitype() {
        return busitype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.busitype
     *
     * @param busitype the value for cz_js_student_reserves.busitype
     * @mbggenerated
     */
    public void setBusitype(Byte busitype) {
        this.busitype = busitype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.drilicnum
     *
     * @return the value of cz_js_student_reserves.drilicnum
     * @mbggenerated
     */
    public String getDrilicnum() {
        return drilicnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.drilicnum
     *
     * @param drilicnum the value for cz_js_student_reserves.drilicnum
     * @mbggenerated
     */
    public void setDrilicnum(String drilicnum) {
        this.drilicnum = drilicnum == null ? null : drilicnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.fstdrilicdate
     *
     * @return the value of cz_js_student_reserves.fstdrilicdate
     * @mbggenerated
     */
    public Date getFstdrilicdate() {
        return fstdrilicdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.fstdrilicdate
     *
     * @param fstdrilicdate the value for cz_js_student_reserves.fstdrilicdate
     * @mbggenerated
     */
    public void setFstdrilicdate(Date fstdrilicdate) {
        this.fstdrilicdate = fstdrilicdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.perdritype
     *
     * @return the value of cz_js_student_reserves.perdritype
     * @mbggenerated
     */
    public String getPerdritype() {
        return perdritype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.perdritype
     *
     * @param perdritype the value for cz_js_student_reserves.perdritype
     * @mbggenerated
     */
    public void setPerdritype(String perdritype) {
        this.perdritype = perdritype == null ? null : perdritype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.traintype
     *
     * @return the value of cz_js_student_reserves.traintype
     * @mbggenerated
     */
    public String getTraintype() {
        return traintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.traintype
     *
     * @param traintype the value for cz_js_student_reserves.traintype
     * @mbggenerated
     */
    public void setTraintype(String traintype) {
        this.traintype = traintype == null ? null : traintype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.apply_fee
     *
     * @return the value of cz_js_student_reserves.apply_fee
     * @mbggenerated
     */
    public BigDecimal getApplyFee() {
        return applyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.apply_fee
     *
     * @param applyFee the value for cz_js_student_reserves.apply_fee
     * @mbggenerated
     */
    public void setApplyFee(BigDecimal applyFee) {
        this.applyFee = applyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.bank_account
     *
     * @return the value of cz_js_student_reserves.bank_account
     * @mbggenerated
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.bank_account
     *
     * @param bankAccount the value for cz_js_student_reserves.bank_account
     * @mbggenerated
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.pay_token
     *
     * @return the value of cz_js_student_reserves.pay_token
     * @mbggenerated
     */
    public String getPayToken() {
        return payToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.pay_token
     *
     * @param payToken the value for cz_js_student_reserves.pay_token
     * @mbggenerated
     */
    public void setPayToken(String payToken) {
        this.payToken = payToken == null ? null : payToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.info_check
     *
     * @return the value of cz_js_student_reserves.info_check
     * @mbggenerated
     */
    public Integer getInfoCheck() {
        return infoCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.info_check
     *
     * @param infoCheck the value for cz_js_student_reserves.info_check
     * @mbggenerated
     */
    public void setInfoCheck(Integer infoCheck) {
        this.infoCheck = infoCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.manager_check
     *
     * @return the value of cz_js_student_reserves.manager_check
     * @mbggenerated
     */
    public Integer getManagerCheck() {
        return managerCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.manager_check
     *
     * @param managerCheck the value for cz_js_student_reserves.manager_check
     * @mbggenerated
     */
    public void setManagerCheck(Integer managerCheck) {
        this.managerCheck = managerCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.exam_check
     *
     * @return the value of cz_js_student_reserves.exam_check
     * @mbggenerated
     */
    public Integer getExamCheck() {
        return examCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.exam_check
     *
     * @param examCheck the value for cz_js_student_reserves.exam_check
     * @mbggenerated
     */
    public void setExamCheck(Integer examCheck) {
        this.examCheck = examCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.shift_seq
     *
     * @return the value of cz_js_student_reserves.shift_seq
     * @mbggenerated
     */
    public String getShiftSeq() {
        return shiftSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.shift_seq
     *
     * @param shiftSeq the value for cz_js_student_reserves.shift_seq
     * @mbggenerated
     */
    public void setShiftSeq(String shiftSeq) {
        this.shiftSeq = shiftSeq == null ? null : shiftSeq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.shift_info
     *
     * @return the value of cz_js_student_reserves.shift_info
     * @mbggenerated
     */
    public String getShiftInfo() {
        return shiftInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.shift_info
     *
     * @param shiftInfo the value for cz_js_student_reserves.shift_info
     * @mbggenerated
     */
    public void setShiftInfo(String shiftInfo) {
        this.shiftInfo = shiftInfo == null ? null : shiftInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.order_status
     *
     * @return the value of cz_js_student_reserves.order_status
     * @mbggenerated
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.order_status
     *
     * @param orderStatus the value for cz_js_student_reserves.order_status
     * @mbggenerated
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.created_at
     *
     * @return the value of cz_js_student_reserves.created_at
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.created_at
     *
     * @param createdAt the value for cz_js_student_reserves.created_at
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.updated_at
     *
     * @return the value of cz_js_student_reserves.updated_at
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.updated_at
     *
     * @param updatedAt the value for cz_js_student_reserves.updated_at
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_student_reserves.deleted_at
     *
     * @return the value of cz_js_student_reserves.deleted_at
     * @mbggenerated
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_student_reserves.deleted_at
     *
     * @param deletedAt the value for cz_js_student_reserves.deleted_at
     * @mbggenerated
     */
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }
}