package org.yzh.web.model.entity;

import java.util.Date;

public class CzJsSchoolAccounts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_school_accounts.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_school_accounts.inscode
     *
     * @mbggenerated
     */
    private String inscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_school_accounts.school_name
     *
     * @mbggenerated
     */
    private String schoolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_school_accounts.merchant_id
     *
     * @mbggenerated
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_school_accounts.bank_type
     *
     * @mbggenerated
     */
    private Integer bankType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_school_accounts.bank_user
     *
     * @mbggenerated
     */
    private String bankUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_school_accounts.bank_name
     *
     * @mbggenerated
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_school_accounts.bank_account
     *
     * @mbggenerated
     */
    private String bankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_school_accounts.sync_status
     *
     * @mbggenerated
     */
    private Integer syncStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_school_accounts.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_school_accounts.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_js_school_accounts.deleted_at
     *
     * @mbggenerated
     */
    private Date deletedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_school_accounts.id
     *
     * @return the value of cz_js_school_accounts.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_school_accounts.id
     *
     * @param id the value for cz_js_school_accounts.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_school_accounts.inscode
     *
     * @return the value of cz_js_school_accounts.inscode
     *
     * @mbggenerated
     */
    public String getInscode() {
        return inscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_school_accounts.inscode
     *
     * @param inscode the value for cz_js_school_accounts.inscode
     *
     * @mbggenerated
     */
    public void setInscode(String inscode) {
        this.inscode = inscode == null ? null : inscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_school_accounts.school_name
     *
     * @return the value of cz_js_school_accounts.school_name
     *
     * @mbggenerated
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_school_accounts.school_name
     *
     * @param schoolName the value for cz_js_school_accounts.school_name
     *
     * @mbggenerated
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_school_accounts.merchant_id
     *
     * @return the value of cz_js_school_accounts.merchant_id
     *
     * @mbggenerated
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_school_accounts.merchant_id
     *
     * @param merchantId the value for cz_js_school_accounts.merchant_id
     *
     * @mbggenerated
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_school_accounts.bank_type
     *
     * @return the value of cz_js_school_accounts.bank_type
     *
     * @mbggenerated
     */
    public Integer getBankType() {
        return bankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_school_accounts.bank_type
     *
     * @param bankType the value for cz_js_school_accounts.bank_type
     *
     * @mbggenerated
     */
    public void setBankType(Integer bankType) {
        this.bankType = bankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_school_accounts.bank_user
     *
     * @return the value of cz_js_school_accounts.bank_user
     *
     * @mbggenerated
     */
    public String getBankUser() {
        return bankUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_school_accounts.bank_user
     *
     * @param bankUser the value for cz_js_school_accounts.bank_user
     *
     * @mbggenerated
     */
    public void setBankUser(String bankUser) {
        this.bankUser = bankUser == null ? null : bankUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_school_accounts.bank_name
     *
     * @return the value of cz_js_school_accounts.bank_name
     *
     * @mbggenerated
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_school_accounts.bank_name
     *
     * @param bankName the value for cz_js_school_accounts.bank_name
     *
     * @mbggenerated
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_school_accounts.bank_account
     *
     * @return the value of cz_js_school_accounts.bank_account
     *
     * @mbggenerated
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_school_accounts.bank_account
     *
     * @param bankAccount the value for cz_js_school_accounts.bank_account
     *
     * @mbggenerated
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_school_accounts.sync_status
     *
     * @return the value of cz_js_school_accounts.sync_status
     *
     * @mbggenerated
     */
    public Integer getSyncStatus() {
        return syncStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_school_accounts.sync_status
     *
     * @param syncStatus the value for cz_js_school_accounts.sync_status
     *
     * @mbggenerated
     */
    public void setSyncStatus(Integer syncStatus) {
        this.syncStatus = syncStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_school_accounts.created_at
     *
     * @return the value of cz_js_school_accounts.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_school_accounts.created_at
     *
     * @param createdAt the value for cz_js_school_accounts.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_school_accounts.updated_at
     *
     * @return the value of cz_js_school_accounts.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_school_accounts.updated_at
     *
     * @param updatedAt the value for cz_js_school_accounts.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_js_school_accounts.deleted_at
     *
     * @return the value of cz_js_school_accounts.deleted_at
     *
     * @mbggenerated
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_js_school_accounts.deleted_at
     *
     * @param deletedAt the value for cz_js_school_accounts.deleted_at
     *
     * @mbggenerated
     */
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }
}