package org.yzh.web.model.entity;

import java.math.BigDecimal;
import java.util.Date;

public class CzOrderRefunds {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_order_refunds.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_order_refunds.stunum
     *
     * @mbggenerated
     */
    private String stunum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_order_refunds.inscode
     *
     * @mbggenerated
     */
    private String inscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_order_refunds.student_name
     *
     * @mbggenerated
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_order_refunds.school_name
     *
     * @mbggenerated
     */
    private String schoolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_order_refunds.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_order_refunds.refund_order_id
     *
     * @mbggenerated
     */
    private Long refundOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_order_refunds.refund_fee
     *
     * @mbggenerated
     */
    private BigDecimal refundFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_order_refunds.refund_remark
     *
     * @mbggenerated
     */
    private String refundRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_order_refunds.merchant_id
     *
     * @mbggenerated
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_order_refunds.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_order_refunds.obj_id
     *
     * @mbggenerated
     */
    private Integer objId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_order_refunds.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_order_refunds.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cz_order_refunds.deleted_at
     *
     * @mbggenerated
     */
    private Date deletedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_order_refunds.id
     *
     * @return the value of cz_order_refunds.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_order_refunds.id
     *
     * @param id the value for cz_order_refunds.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_order_refunds.stunum
     *
     * @return the value of cz_order_refunds.stunum
     *
     * @mbggenerated
     */
    public String getStunum() {
        return stunum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_order_refunds.stunum
     *
     * @param stunum the value for cz_order_refunds.stunum
     *
     * @mbggenerated
     */
    public void setStunum(String stunum) {
        this.stunum = stunum == null ? null : stunum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_order_refunds.inscode
     *
     * @return the value of cz_order_refunds.inscode
     *
     * @mbggenerated
     */
    public String getInscode() {
        return inscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_order_refunds.inscode
     *
     * @param inscode the value for cz_order_refunds.inscode
     *
     * @mbggenerated
     */
    public void setInscode(String inscode) {
        this.inscode = inscode == null ? null : inscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_order_refunds.student_name
     *
     * @return the value of cz_order_refunds.student_name
     *
     * @mbggenerated
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_order_refunds.student_name
     *
     * @param studentName the value for cz_order_refunds.student_name
     *
     * @mbggenerated
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_order_refunds.school_name
     *
     * @return the value of cz_order_refunds.school_name
     *
     * @mbggenerated
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_order_refunds.school_name
     *
     * @param schoolName the value for cz_order_refunds.school_name
     *
     * @mbggenerated
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_order_refunds.order_id
     *
     * @return the value of cz_order_refunds.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_order_refunds.order_id
     *
     * @param orderId the value for cz_order_refunds.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_order_refunds.refund_order_id
     *
     * @return the value of cz_order_refunds.refund_order_id
     *
     * @mbggenerated
     */
    public Long getRefundOrderId() {
        return refundOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_order_refunds.refund_order_id
     *
     * @param refundOrderId the value for cz_order_refunds.refund_order_id
     *
     * @mbggenerated
     */
    public void setRefundOrderId(Long refundOrderId) {
        this.refundOrderId = refundOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_order_refunds.refund_fee
     *
     * @return the value of cz_order_refunds.refund_fee
     *
     * @mbggenerated
     */
    public BigDecimal getRefundFee() {
        return refundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_order_refunds.refund_fee
     *
     * @param refundFee the value for cz_order_refunds.refund_fee
     *
     * @mbggenerated
     */
    public void setRefundFee(BigDecimal refundFee) {
        this.refundFee = refundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_order_refunds.refund_remark
     *
     * @return the value of cz_order_refunds.refund_remark
     *
     * @mbggenerated
     */
    public String getRefundRemark() {
        return refundRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_order_refunds.refund_remark
     *
     * @param refundRemark the value for cz_order_refunds.refund_remark
     *
     * @mbggenerated
     */
    public void setRefundRemark(String refundRemark) {
        this.refundRemark = refundRemark == null ? null : refundRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_order_refunds.merchant_id
     *
     * @return the value of cz_order_refunds.merchant_id
     *
     * @mbggenerated
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_order_refunds.merchant_id
     *
     * @param merchantId the value for cz_order_refunds.merchant_id
     *
     * @mbggenerated
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_order_refunds.type
     *
     * @return the value of cz_order_refunds.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_order_refunds.type
     *
     * @param type the value for cz_order_refunds.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_order_refunds.obj_id
     *
     * @return the value of cz_order_refunds.obj_id
     *
     * @mbggenerated
     */
    public Integer getObjId() {
        return objId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_order_refunds.obj_id
     *
     * @param objId the value for cz_order_refunds.obj_id
     *
     * @mbggenerated
     */
    public void setObjId(Integer objId) {
        this.objId = objId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_order_refunds.created_at
     *
     * @return the value of cz_order_refunds.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_order_refunds.created_at
     *
     * @param createdAt the value for cz_order_refunds.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_order_refunds.updated_at
     *
     * @return the value of cz_order_refunds.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_order_refunds.updated_at
     *
     * @param updatedAt the value for cz_order_refunds.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cz_order_refunds.deleted_at
     *
     * @return the value of cz_order_refunds.deleted_at
     *
     * @mbggenerated
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cz_order_refunds.deleted_at
     *
     * @param deletedAt the value for cz_order_refunds.deleted_at
     *
     * @mbggenerated
     */
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }
}