package org.yzh.web.mapper;

import org.apache.ibatis.annotations.Param;

import java.util.List;


public interface BaseMapper<T> {

    List<T> select(T t);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated
     */
    int insert(T t);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated
     */
    int insertSelective(T t);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated
     */
    T selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(T t);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(T t);

    T find(@Param("where") String where,@Param("sort") String sort);

    T find(@Param("where") String where);
}